# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Install tkinter and X virtual framebuffer
RUN apt-get update \
    && apt-get install -y python3-tk xvfb \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir .

# Use xvfb-run to provide a virtual display for tkinter
ENTRYPOINT ["xvfb-run", "-a", "hitl-mcp-server"]
